export default {
  index: 'Overview',
  servers: 'Media Servers',
  environment: 'Environment Variables',
  automations: 'Automations',
  realtime: 'Real-Time Updates',
  requests: 'Seerr Requests',
  tailscale: 'Tailscale VPN',
  destinations: 'Notification Destinations',
  email: 'Email & Newsletters',
  backup: 'Backup & Restore',
  recovery: 'Account Recovery',
  mobile: 'Mobile App',
  debug: 'Debug Page',
};
